# Generated by Django 4.2.5 on 2024-07-29 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 29, 15, 13, 59, 511018)),
        ),
    ]
