# Generated by Django 4.2.5 on 2024-07-29 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 29, 17, 47, 45, 991543)),
        ),
    ]
