# Generated by Django 4.2.5 on 2024-07-30 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 30, 17, 16, 51, 771500)),
        ),
    ]
